name: flutter_login_architecture

description: Authentication for VRP application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_core_web: ^2.6.0
  firebase_auth: ^4.6.3
  firebase_auth_web: ^5.5.3
  firebase_database: ^10.2.3
  cloud_firestore: ^4.8.1

  google_maps_flutter: ^2.3.1
  google_maps_flutter_web: ^0.5.0+1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_polyline_points: ^1.0.0

  provider: ^6.0.5
  dropdown_button2: ^2.1.4
  rxdart: ^0.27.7
  permission_handler: ^10.3.0
  http: ^1.0.0
  shared_preferences: ^2.1.2
  android_alarm_manager_plus: ^3.0.1
  url_launcher: ^6.1.11
  flutter_inappwebview: ^5.7.2+3
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_maps: ^22.1.36
  cupertino_icons: ^1.0.5

dependency_overrides:
  http: ^0.13.1